---
title: Tacticsjournal.Com
timezone: UTC
collections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: category
  values:
    layout: category
name: Tactics Journal
description: Analayzing football tactics
avatar: https://pbs.twimg.com/profile_images/1608846415756726272/i-zIF5TR_400x400.jpg
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: rss
  twitter: TacticsJournal
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: G-4M4JSZWQE3
url: https://tacticsjournal.com
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-admin
- decap
future: false
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
