name: Schedule Posts

on:
  schedule:
    - cron: '43 21 * * *'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages build
        uses: wei/curl@master
        with:
          args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/kyleboas/tacticsjournal.com/pages/builds"
